### ISSUE TITLE
Doesn't work on Replit.

### ISSUE THREAD

**Issue by TrashUwU** [meister03/discord-cross-hosting#14]
I've done everything you've shown in guide. But machine 1 and machine 2 can't connect to bridge. Error log:
```
[CM] [Connect] Connecting to Bridge with the given Data
[CM] [Connect] Connecting to Bridge with the given Data
HTTP/1.0 400 Bad Request
```

**Comment by meister03** [comment]
Replit changed sth it worked earlier

**Comment by TrashUwU** [comment]
> Replit changed sth it worked earlier

Can you make sure it doesn't work with your bot? Maybe I've done something in the code.

**Comment by RumiDaNeko** [comment]
maybe now replit only allow http....

**Comment by meister03** [comment]
replit is not intended for this packages. We will not officially support it
