### ISSUE TITLE
Publish last change with typescript on npm

### ISSUE THREAD

**Issue by kvaillant** [meister03/discord-cross-hosting#16]
Hey thanks for this amazing lib. I was having some troubles lately with the latest version published on npm vs this repo sources. 
After diving into the npm source code I realised some issues where already addressed on github ^^.

I add then to checkout the lib as a github dependencies instead of npm

**Comment by meister03** [comment]
Are you using the ts rewrite?

**Comment by meister03** [comment]
It still has som3 bugs
