### ISSUE TITLE
Cluster not killed when rolling restart

### ISSUE THREAD

**Issue by ghost** [meister03/discord-cross-hosting#5]
Whenever the Client (Cluster.js) reconnected to Bridge after the Bridge restarted, the Client will not check the shardData, which cause the Client not rolling restart when the Bridge restart with a different shardData

**Comment by meister03** [comment]
Could you show your client options in the cluster.js file

**Comment by ghost** [comment]
const client = new Client({
	agent: "bot",
	host: "localhost",
	port: 4423,
	authToken: "abc",
	retries: 1000 * 10,
	rollingRestarts: true,
});

**Comment by meister03** [comment]
The Bridge emits a message after 10s, whenever it restarts with the new ShardList.
Do you have a listener on the debug event?

A rollingrestart will not take place, when the shardList on the client clusters, did not changed....

**Comment by ghost** [comment]
I don't know why, but after i have tried it few more times, the problem isn't happen anymore, the cluster can retreive the shard data message from bridge after reconnected to the bridge and able to restart

**Comment by ghost** [comment]
But I found another problem that the oldCluster isn't actually killed after rollingRestart

**Comment by ghost** [comment]
The bot respond twice, which means there are two processes

**Comment by meister03** [comment]
Could send me the Shardclusterlist.
.rollingRestart seems to be buggy...

**Comment by ghost** [comment]
[[[0],[1],[2],[3],[4]]]

**Comment by meister03** [comment]
And the new/old one?

**Comment by ghost** [comment]
new: [[[0],[1],[2],[3]]]

**Comment by ghost** [comment]
im only testing rollingRestart so i only remove one shard

**Comment by meister03** [comment]
And Cluster 4 is not killed, when I understood correctly.

Could you provide me the version of discord-hybrid-sharding & cross-hosting

**Comment by ghost** [comment]
I mean all the cluster spawned by the Cluster.js with oldData isnt killed when restart and it cause the bot is logged in with two processes (new cluster and old cluster) as old cluster not killed

i use latest version for both packages

**Comment by ghost** [comment]
not only the cluster i removed

**Comment by meister03** [comment]
Lastest means? I update the pkgs daily. I need the version numbers lol

**Comment by ghost** [comment]
"discord-cross-hosting": "^2.1.4",
"discord-hybrid-sharding": "^1.4.2",

**Comment by meister03** [comment]
I will try to reproduce the issue, thx for the info

**Comment by meister03** [comment]
@ZetraDev  Could you test `^2.15` `discord-cross-hosting`
Pushed a test fix, I am thinking it is a issue with the spawn function

**Comment by ghost** [comment]
The cluster still isn't killed after restart, since the problem was happen because of the cluster isn't killed, i think that the problem is related to the kill function of cluster instead of spawn function (as the cluster spawned successfully)

**Comment by ghost** [comment]
i use 2.1.6

**Comment by meister03** [comment]
How do you check that the cluster was not killed?

**Comment by ghost** [comment]
i check it by see how many times it respond my message in discord channel

**Comment by meister03** [comment]
Have a guess, thats a issue with test bots.
That on a higher count, shards get same guilds assigned, which causes that you recieve the message event double.

Could you rather setup a task and check:
```js
setInterval(() => {}
    console.log(`ClusterClient ${client.cluster.id} online with ${client.cluster.count}`)
, 3000)
```

**Comment by LOLBRUHNICE** [comment]
In cluster.js or bot.js?

**Comment by Yoinky3000** [comment]
Somehow the problem actually solved after i add the code above into the file XD, but I found two more problem AGAIN when i look at the log from the code you told me to add lol!
1. the manager didnt delete the cluster id I removed (like if i start with list [[[0],[1],[2],[3],[4]]] and restart with [[[0],[1],[2],[3]]], the 4th cluster(id 4) isnt killed)
2. the bridge cannot run broadcasteval successfully(cannot get data normally like `this.guild.cache.size`, it returns `[ { } ]` instead of `[ [ xx,xx,xx ] ]`) after I restart bridge with reducing the amount of totalshard (it doesn't happen if I restart with increasing the amount of totalshard), so I think it is related to problem 1

**Comment by meister03** [comment]
Yes, problem 2 is connected with problem 1.
I tested that case, I can test it today again 🤔

**Comment by meister03** [comment]
![image](https://user-images.githubusercontent.com/69507874/148288282-78761474-2e1e-44d1-9b04-f71e96df7ae9.png)
Do you have this line in your Code?

**Comment by meister03** [comment]
![image](https://user-images.githubusercontent.com/69507874/148289065-c31e84b0-48f4-4a15-bf42-5e95d5b60f19.png)
I am  unable to reproduce the issue. Could clear the node_modules cache and reinstall the versions....

**Comment by meister03** [comment]
I do not know maybe your problem is connected with `.shardClusterList`, which was written in small case, but was not up-to-date with hybrid-sharding@latest.
Updated `discord-cross-hosting`, could you kindly upgrade the version :)

**Comment by Yoinky3000** [comment]
After i upgrade all packages to latest, I still get `[ { } ]` when i use broadcasteval, but this time it only happen when restarting

**Comment by meister03** [comment]
The `{}` only happens, when the broadcastEval does not resolve, bc their are issues in the IPC.

I did not encountered this issue, but will try to reproduce it today.
